"""
Exercise 3: Stream to File
Stream a long clinical report and save it to a file simultaneously.

Skills practiced:
- Streaming and writing to file at the same time
- Generating structured clinical documents
- Handling long-form streaming content
- File output for clinical documentation

Healthcare context:
  Clinical reports (discharge summaries, care plans, progress notes) are
  often long. Streaming lets you display them in real-time while ALSO
  saving to a file for the medical record or EHR integration.
"""

import os
import sys
import time
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# ============================================================
# Stream to Display AND File Simultaneously
# ============================================================

def stream_to_file(messages, output_path, max_tokens=1500):
    """
    Stream response to both terminal display and a file.
    Returns: (full_content, stats_dict)
    """
    start_time = time.time()
    first_token_time = None
    full_content = ""
    chunk_count = 0

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    try:
        stream = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            max_tokens=max_tokens,
            stream=True
        )

        # Open file for writing while streaming
        with open(output_path, "w") as f:
            # Write header to file
            header = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n{'=' * 60}\n\n"
            f.write(header)

            for chunk in stream:
                if chunk.choices[0].delta.content is not None:
                    token = chunk.choices[0].delta.content

                    if first_token_time is None:
                        first_token_time = time.time()

                    # Write to BOTH terminal and file
                    print(token, end="", flush=True)
                    f.write(token)
                    f.flush()  # Flush file buffer too — ensures real-time writing

                    full_content += token
                    chunk_count += 1

            # Write footer to file
            f.write(f"\n\n{'=' * 60}\n")
            f.write(f"Generated by AI Clinical Documentation System\n")
            f.write(f"Model: gpt-4o-mini | Tokens: {chunk_count} chunks\n")
            f.write(f"DISCLAIMER: For educational purposes only.\n")

        print()  # Newline after stream

    except Exception as e:
        print(f"\n❌ Error: {e}")
        return None, {}

    end_time = time.time()
    stats = {
        "first_token_ms": round((first_token_time - start_time) * 1000) if first_token_time else 0,
        "total_time_s": round(end_time - start_time, 2),
        "chunks": chunk_count,
        "characters": len(full_content),
        "file_path": output_path,
        "file_size_bytes": os.path.getsize(output_path),
    }

    return full_content, stats


# ============================================================
# Demo 1: Discharge Summary to File
# ============================================================

def demo_discharge_summary():
    """Generate and stream a discharge summary to file"""
    print("\n" + "=" * 70)
    print("DEMO 1: STREAM DISCHARGE SUMMARY TO FILE")
    print("=" * 70)

    output_file = "output_discharge_summary.txt"

    messages = [
        {"role": "system", "content": """You are a clinical documentation specialist.
Generate a detailed discharge summary following this structure:

DISCHARGE SUMMARY
═════════════════
PATIENT: [Generate realistic name]
MRN: [Generate sample MRN]
ADMISSION DATE: 2026-02-15
DISCHARGE DATE: 2026-02-21
ATTENDING: Dr. [Name]

ADMISSION DIAGNOSIS:
DISCHARGE DIAGNOSIS:

HISTORY OF PRESENT ILLNESS:
[2-3 paragraph narrative]

HOSPITAL COURSE:
[Detailed day-by-day or category-based description]

SIGNIFICANT FINDINGS:
- Labs:
- Imaging:
- Procedures:

DISCHARGE MEDICATIONS:
[Numbered list with dose, route, frequency, indication]

DISCHARGE CONDITION:

DISCHARGE INSTRUCTIONS:
[Detailed patient instructions]

FOLLOW-UP APPOINTMENTS:

PENDING RESULTS:

This is for educational/training purposes only."""},
        {"role": "user", "content": """Generate a discharge summary for:
68-year-old male admitted for acute exacerbation of heart failure.
History: HFrEF (EF 30%), type 2 diabetes, CKD stage 3, atrial fibrillation.
Course: Required IV diuresis for 4 days, converted back to oral meds, 
weight came down 8 kg, symptoms improved, BNP trending down.
Home on optimized heart failure meds."""}
    ]

    print(f"\n📝 Generating and streaming to '{output_file}'...\n")
    print("─" * 70)

    content, stats = stream_to_file(messages, output_file, max_tokens=2000)

    print(f"\n{'─' * 70}")
    print(f"\n✅ SAVED TO FILE: {stats['file_path']}")
    print(f"   📊 File size: {stats['file_size_bytes']} bytes")
    print(f"   ⏱️  TTFT: {stats['first_token_ms']}ms | Total: {stats['total_time_s']}s")
    print(f"   📦  Chunks: {stats['chunks']} | Chars: {stats['characters']}")


# ============================================================
# Demo 2: Care Plan to File
# ============================================================

def demo_care_plan():
    """Generate a comprehensive care plan"""
    print("\n" + "=" * 70)
    print("DEMO 2: STREAM CARE PLAN TO FILE")
    print("=" * 70)

    output_file = "output_care_plan.txt"

    messages = [
        {"role": "system", "content": """You are a clinical care coordinator. Generate a comprehensive,
multidisciplinary care plan. Include:
- Problem list (prioritized)
- Goals for each problem (SMART goals)
- Interventions (medications, therapies, monitoring)
- Responsible providers
- Timeline and milestones
- Patient education needs
- Follow-up schedule
Educational purposes only."""},
        {"role": "user", "content": """Create a care plan for:
55-year-old female with newly diagnosed Type 2 Diabetes (HbA1c 9.2%), 
obesity (BMI 38), depression (PHQ-9: 15), hypertension (BP 155/92),
and pre-diabetic retinopathy found on screening eye exam.
She works as a teacher, has limited time for appointments, 
and is motivated but overwhelmed by the number of new diagnoses."""}
    ]

    print(f"\n📝 Generating care plan to '{output_file}'...\n")
    print("─" * 70)

    content, stats = stream_to_file(messages, output_file, max_tokens=2000)

    print(f"\n{'─' * 70}")
    print(f"\n✅ SAVED: {stats['file_path']} ({stats['file_size_bytes']} bytes)")
    print(f"   ⏱️  {stats['total_time_s']}s | {stats['chunks']} chunks")


# ============================================================
# Demo 3: Multiple Reports in Batch
# ============================================================

def demo_batch_reports():
    """Generate multiple clinical reports to separate files"""
    print("\n" + "=" * 70)
    print("DEMO 3: BATCH CLINICAL REPORTS")
    print("=" * 70)

    reports = [
        {
            "name": "Progress Note",
            "file": "output_progress_note.txt",
            "messages": [
                {"role": "system", "content": "You are a physician writing a SOAP progress note. Be concise but thorough. Educational purposes only."},
                {"role": "user", "content": "Write a progress note for day 3 of admission: 72M admitted for pneumonia, on levofloxacin, improving. Cough decreasing, O2 now 95% on RA (was 89% on admission). WBC trending down from 15.2 to 11.8. Appetite returning."}
            ],
            "max_tokens": 600,
        },
        {
            "name": "Consultation Note",
            "file": "output_consult_note.txt",
            "messages": [
                {"role": "system", "content": "You are a cardiologist writing a consultation note. Be professional and thorough. Educational purposes only."},
                {"role": "user", "content": "Cardiology consult for 65F with new onset atrial fibrillation found on telemetry after hip replacement surgery. Rate 120s, asymptomatic. PMH: HTN, DM2. CHA2DS2-VASc would be calculated."}
            ],
            "max_tokens": 800,
        },
        {
            "name": "Referral Letter",
            "file": "output_referral.txt",
            "messages": [
                {"role": "system", "content": "You are a PCP writing a referral letter to a specialist. Professional and concise. Educational purposes only."},
                {"role": "user", "content": "Refer 45M to GI for persistent GERD despite 8 weeks of omeprazole 40mg BID, now with dysphagia to solids. Needs EGD. PMH: obesity, smoking."}
            ],
            "max_tokens": 500,
        },
    ]

    print(f"\n📄 Generating {len(reports)} clinical reports...\n")

    for i, report in enumerate(reports, 1):
        print(f"\n{'═' * 70}")
        print(f"📝 Report {i}/{len(reports)}: {report['name']} → {report['file']}")
        print(f"{'═' * 70}\n")

        content, stats = stream_to_file(report["messages"], report["file"], report["max_tokens"])

        print(f"\n   ✅ Saved ({stats['file_size_bytes']} bytes, {stats['total_time_s']}s)")

    print(f"\n{'═' * 70}")
    print("📁 ALL FILES GENERATED:")
    for report in reports:
        if os.path.exists(report["file"]):
            size = os.path.getsize(report["file"])
            print(f"   📄 {report['file']} ({size} bytes)")


# ============================================================
# Main Menu
# ============================================================

def main():
    print("\n💾 Exercise 3: Stream to File")
    print("=" * 70)
    print("Stream clinical reports to display AND file simultaneously\n")

    print("Choose a demo:")
    print("1. Discharge summary (stream to file)")
    print("2. Care plan (stream to file)")
    print("3. Batch reports (3 clinical documents)")
    print("4. Run all")

    choice = input("\nEnter choice (1-4): ").strip()

    if choice == "1":
        demo_discharge_summary()
    elif choice == "2":
        demo_care_plan()
    elif choice == "3":
        demo_batch_reports()
    elif choice == "4":
        demo_discharge_summary()
        demo_care_plan()
        demo_batch_reports()
    else:
        print("Invalid choice")

    print(f"""
{'═' * 70}
KEY LEARNINGS:
{'═' * 70}
1. Open file + stream in same loop → write and display simultaneously
2. f.flush() ensures data is written to disk in real-time (not buffered)
3. Add metadata (timestamp, model, disclaimer) to generated files
4. Batch generation is useful for clinical documentation workflows
5. File output can feed into EHR import, PDF generation, or email

🏥 PRODUCTION USE CASES:
   • Discharge summaries → auto-populate EHR discharge module
   • Progress notes → pre-fill for physician review and sign-off
   • Referral letters → generate, review, send via secure messaging
   • Care plans → PDF for patient portal
   
   The pattern: Stream → Display → Save → Integrate
""")


if __name__ == "__main__":
    main()
